Fix do not override built history
gridsuite/network-modification-server pull request #114
Opened 2022-08-02 08:25 UTC by laurgarn

2022-08-04 13:32 UTC, niconoir requested changes
Minor comments.

2022-08-04 13:32 UTC, niconoir commented on src/main/java/org/gridsuite/modification/server/dto/GroupAndReportInfos.java
> +package org.gridsuite.modification.server.dto;
Missing license header

2022-08-04 13:32 UTC, niconoir commented on src/main/java/org/gridsuite/modification/server/service/NetworkModificationService.java
> +    private static final Logger LOGGER = LoggerFactory.getLogger("details");
Was LOGGER created for debug purpose ?

2022-08-04 13:32 UTC, niconoir commented on src/main/java/org/gridsuite/modification/server/service/NetworkModificationService.java
> +        LOGGER.info("About to add report of uuid {}", reportUuid);
Was this logged for debug purpose ?

2022-08-04 13:32 UTC, niconoir commented on src/main/java/org/gridsuite/modification/server/dto/BuildInfos.java
> +    public List<UUID> getModificationGroupUuids() {
This method seems to be unused.

2022-08-05 13:59 UTC, laurgarn commented on src/main/java/org/gridsuite/modification/server/dto/GroupAndReportInfos.java
> +package org.gridsuite.modification.server.dto;
Added

2022-08-05 13:59 UTC, laurgarn commented on src/main/java/org/gridsuite/modification/server/service/NetworkModificationService.java
> +    private static final Logger LOGGER = LoggerFactory.getLogger("details");
Removed

2022-08-05 14:00 UTC, laurgarn commented on src/main/java/org/gridsuite/modification/server/service/NetworkModificationService.java
> +        LOGGER.info("About to add report of uuid {}", reportUuid);
Yes, removed

2022-08-05 14:10 UTC, niconoir approved these changes

2022-08-05 14:24 UTC, merged