Use powsybl modification class to modify network
gridsuite/network-modification-server pull request #115
Opened 2022-08-04 11:42 UTC by SlimaneAmar

Signed-off-by: Slimane AMAR <slimane.amar@rte-france.com>

2022-08-17 12:52 UTC, FranckLecuyer requested changes

2022-08-18 06:59 UTC, SlimaneAmar commented on src/main/java/org/gridsuite/modification/server/NetworkModificationController.java
> +        return ResponseEntity.ok().body(networkModificationService.splitLineWithVoltageLevel(networkUuid, variantId, new GroupAndReportInfos(groupUuid, reportUuid), lineSplitWithVoltageLevelInfos));
yes

2022-11-16 21:02 UTC, geofjamg approved these changes
@SlimaneAmar much cleaner and extensible than main branch!

2022-11-17 14:19 UTC, FranckLecuyer requested changes

2022-11-17 16:53 UTC, SlimaneAmar commented on src/main/java/org/gridsuite/modification/server/modifications/SplitLineWithVoltageLevel.java
> +        algo.apply(network, false, subReporter);
Done

2022-11-17 16:53 UTC, SlimaneAmar commented on src/main/resources/config/application.yaml
> +    allow-circular-references: true
Removed

2022-11-17 16:58 UTC, FranckLecuyer approved these changes

2022-11-17 16:59 UTC, merged