remove elasticsearch mock
gridsuite/network-modification-server pull request #164
Opened 2022-11-29 15:17 UTC by anistouri

2022-11-30 13:04 UTC, jonenst approved these changes

2022-12-13 16:12 UTC, SlimaneAmar requested changes

2022-12-13 16:12 UTC, SlimaneAmar commented on src/main/java/org/gridsuite/modification/server/elasticsearch/ESConfig.java
> +    public EquipmentInfosService equipmentInfosService(EquipmentInfosRepository equipmentInfosRepository, TombstonedEquipmentInfosRepository tombstonedEquipmentInfosRepository) {
Remove this code
Annoted the class EquipmentInfosService as a service

2022-12-20 10:46 UTC, SlimaneAmar approved these changes

2022-12-22 10:38 UTC, merged