Refactor LoadModification GroovyScript and EquipmentDeletion with generic design
gridsuite/network-modification-server pull request #181
Opened 2022-12-28 15:06 UTC by ayolab

Signed-off-by: Ayoub LABIDI <ayoub.labidi@protonmail.com>

2023-01-03 10:43 UTC, laurgarn reviewed
Code seems OK

2023-01-05 09:09 UTC, SlimaneAmar commented on src/test/java/org/gridsuite/modification/server/ModificationControllerTest.java
> -
I'm not sure that all the tests have been preserved

2023-01-11 16:17 UTC, dbraquart requested changes
tests: ok
code: a few changes to address

2023-01-12 16:05 UTC, dbraquart commented on src/main/java/org/gridsuite/modification/server/modifications/GroovyScriptModification.java
> +/**
good job !

2023-01-12 16:52 UTC, dbraquart requested changes
Front-end tests : ok
review: ok, just a modifier to add please

2023-01-12 17:06 UTC, ayolab commented on src/main/java/org/gridsuite/modification/server/entities/GroovyScriptEntity.java
> +    void assignAttributes(GroovyScriptInfos modificationInfos) {
Done

2023-01-12 17:34 UTC, dbraquart approved these changes

2023-01-16 08:56 UTC, SlimaneAmar approved these changes

2023-01-16 08:57 UTC, merged