Update Shunt Compensator endpoint
gridsuite/network-modification-server pull request #214
Opened 2023-02-20 09:03 UTC by ayolab

2023-02-21 14:37 UTC, FranckLecuyer approved these changes

2023-02-21 14:43 UTC, FranckLecuyer requested changes

2023-02-21 14:43 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/modification/server/modifications/ShuntCompensatorCreation.java
> +            Double susceptancePerSection = modificationInfos.getQAtNominalV() / (voltageLevel.getNominalV() * voltageLevel.getNominalV());
Math.pow(voltageLevel.getNominalV(), 2)

2023-02-27 08:27 UTC, FranckLecuyer approved these changes

2023-02-28 10:21 UTC, YenguiSeddik approved these changes

2023-02-28 10:21 UTC, YenguiSeddik approved these changes

2023-02-28 13:56 UTC, merged