add check qmax must be greater than qmin when modifying generator
gridsuite/network-modification-server pull request #245
Opened 2023-05-10 14:43 UTC by Walid-Sahnoun

2023-05-12 09:07 UTC, FranckLecuyer requested changes

2023-05-15 12:13 UTC, Walid-Sahnoun commented on src/main/java/org/gridsuite/modification/server/modifications/GeneratorModification.java
> +            }
checks added

2023-05-15 13:28 UTC, FranckLecuyer requested changes

2023-05-15 13:28 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/modification/server/modifications/GeneratorModification.java
> +            throw makeGeneratorException(modificationInfos.getEquipmentId(), "maximum reactive power" + maxReactivePower + "is expected to be greater than or equal to minimum reactive power" + minRea
add space before and after the values in the message

2023-05-15 13:56 UTC, FranckLecuyer approved these changes

2023-05-15 15:46 UTC, ayolab approved these changes

2023-05-16 08:19 UTC, merged