add check on the hypothese automatic test status
gridsuite/network-modification-server pull request #251
Opened 2023-05-22 13:54 UTC by ghazwarhili

2023-05-26 14:22 UTC, ghazwarhili commented
tu as une proposition pour le renommage assertNetworkAfter* ?

2023-05-31 08:44 UTC, SlimaneAmar requested changes

2023-05-31 08:44 UTC, SlimaneAmar commented on src/main/java/org/gridsuite/modification/server/dto/NetworkModificationResult.java
> +        return !Objects.equals(this.applicationStatus, ApplicationStatus.WITH_ERRORS);
this.applicationStatus != ApplicationStatus.WITH_ERRORS

2023-05-31 08:47 UTC, SlimaneAmar commented
Need add the test wherever we make a http request like `AbstractNetworkModificationTest` and other unit test classes

2023-06-22 12:18 UTC, SlimaneAmar requested changes

2023-06-22 12:18 UTC, SlimaneAmar commented on src/test/java/org/gridsuite/modification/server/modifications/AbstractNetworkModificationTest.java
> +        Optional<NetworkModificationResult> networkModificationResult = mapper.readValue(mvcResult.getResponse().getContentAsString(), new TypeReference<>() { });
Need test the status

2023-08-09 08:40 UTC, closed without merging