Fix section id error
gridsuite/network-modification-server pull request #254
Opened 2023-05-24 12:52 UTC by anistouri

2023-05-24 13:28 UTC, FranckLecuyer requested changes

2023-05-24 13:28 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/modification/server/modifications/ModificationUtils.java
> +                    .build().apply(network, false, LocalComputationManager.getDefault(), subReporter);
.build().apply(network, subReporter) is sufficient

2023-05-24 14:18 UTC, FranckLecuyer approved these changes

2023-05-24 14:55 UTC, FranckLecuyer approved these changes

2023-05-25 08:50 UTC, ayolab approved these changes

2023-05-25 08:56 UTC, merged