Each modifications group now have a dedicated application status
gridsuite/network-modification-server pull request #274
Opened 2023-06-19 15:20 UTC by Meklo

2023-06-21 14:05 UTC, Walid-Sahnoun commented on src/main/java/org/gridsuite/modification/server/dto/NetworkModificationResult.java
> +import java.util.*;
no need to import the whole library

2023-06-21 14:12 UTC, Walid-Sahnoun commented on src/test/java/org/gridsuite/modification/server/Impacts/ElementImpactTest.java
> +import java.util.*;
same here

2023-06-22 12:53 UTC, SlimaneAmar requested changes

2023-06-22 12:53 UTC, SlimaneAmar commented on src/main/java/org/gridsuite/modification/server/dto/NetworkModificationResult.java
> +    @Schema(description = "Operation application status")
Modification application status or Network modification application status ?

2023-06-22 12:53 UTC, SlimaneAmar commented on src/main/java/org/gridsuite/modification/server/dto/NetworkModificationResult.java
>      ApplicationStatus applicationStatus;
Remove it

2023-06-27 09:58 UTC, AbdelHedhili commented on src/main/java/org/gridsuite/modification/server/modifications/NetworkModificationApplicator.java
> +                .collect(Collectors.toList());
`.collect(Collectors.toList());` -> `toList();`

2023-06-27 11:49 UTC, Meklo commented on src/main/java/org/gridsuite/modification/server/modifications/NetworkModificationApplicator.java
> +                .collect(Collectors.toList());
Done

2023-06-27 11:49 UTC, Meklo commented on src/test/java/org/gridsuite/modification/server/Impacts/ElementImpactTest.java
> +import java.util.*;
Done

2023-06-27 11:50 UTC, Meklo commented on src/main/java/org/gridsuite/modification/server/dto/NetworkModificationResult.java
> +import java.util.*;
Done

2023-06-27 12:23 UTC, AbdelHedhili requested changes

2023-06-27 12:23 UTC, AbdelHedhili commented on src/main/java/org/gridsuite/modification/server/service/NetworkModificationService.java
the field reportService is no longer used.

2023-06-27 12:44 UTC, Meklo commented on src/main/java/org/gridsuite/modification/server/service/NetworkModificationService.java
I removed it

2023-06-27 12:44 UTC, AbdelHedhili approved these changes

2023-06-27 12:47 UTC, SlimaneAmar approved these changes

2023-06-27 12:49 UTC, SlimaneAmar commented
Review OK
Test OK

2023-06-27 14:18 UTC, Walid-Sahnoun approved these changes
code ok
test ok

2023-07-06 10:19 UTC, merged