[WIP] Add TWT ratio tap changer modification
gridsuite/network-modification-server pull request #276
Opened 2023-06-21 14:15 UTC by ayolab

2023-07-17 17:31 UTC, dbraquart commented on src/main/java/org/gridsuite/modification/server/modifications/TwoWindingsTransformerModification.java
> +                    RatioTapChangerStep ratioStep = (RatioTapChangerStep) step;
this line can be deleted if you use:  
if (step instanceof RatioTapChangerStep ratioStep) {

2023-07-17 17:31 UTC, dbraquart commented on src/main/java/org/gridsuite/modification/server/modifications/TwoWindingsTransformerModification.java
> +                    PhaseTapChangerStep phaseStep = (PhaseTapChangerStep) step;
same trick here

2023-07-17 17:35 UTC, dbraquart commented on src/main/java/org/gridsuite/modification/server/modifications/TwoWindingsTransformerModification.java
> +            addStepAttributeReport(tapChangerStepsReports, "newStepConductance" + step.getX(),
must be step.getG() here

2023-07-18 14:54 UTC, archendel approved these changes

2023-07-19 13:21 UTC, dbraquart requested changes
code: simplify 2 cast
tests: cf Front PR

2023-07-19 13:25 UTC, dbraquart commented on src/main/java/org/gridsuite/modification/server/modifications/TwoWindingsTransformerModification.java
> +                    RatioTapChangerStep ratioStep = (RatioTapChangerStep) step;
you can combine 2 lines in a single one

2023-07-19 13:28 UTC, dbraquart approved these changes
code ok
tests: done, see Front's PR

2023-07-24 14:33 UTC, merged