[WIP] Add phase tap to twt modification
gridsuite/network-modification-server pull request #278
Opened 2023-06-29 15:58 UTC by Meklo

2023-07-19 09:21 UTC, archendel commented on src/main/java/org/gridsuite/modification/server/entities/equipment/modification/TwoWindingsTransformerModificationEntity.java
> +            phaseTapChangerStepsEmbeddable = getTapChangerSteps().stream().filter(step -> step.getTapChangerType().equals(TapChangerType.PHASE)).sorted(Comparator.comparing(TapChangerStepCreationEmbe
try to use groupingBy instead or browsing the list twice ?

2023-07-19 09:21 UTC, archendel commented on src/test/java/org/gridsuite/modification/server/ModificationControllerTest.java
> +        assertEquals(10, vl.getConnectableCount());
Why has it increased ?

2023-07-19 09:21 UTC, archendel commented on src/test/java/org/gridsuite/modification/server/modifications/TwoWindingsTransformerModificationTest.java
> +                        .build())
Should it be needed ?

2023-07-19 09:21 UTC, archendel commented on src/test/java/org/gridsuite/modification/server/modifications/TwoWindingsTransformerModificationTest.java
> +                        .build())
should it be needed ?

2023-07-24 16:04 UTC, dbraquart requested changes
code: just minor changes requested
tests: see Front PR

2023-07-31 17:34 UTC, dbraquart requested changes
code: just a question to adress
tests: ok

2023-08-01 07:45 UTC, dbraquart approved these changes
code: ok
tests: not done since last review

2023-08-01 09:59 UTC, archendel approved these changes

2023-08-01 13:51 UTC, dbraquart approved these changes
code: ok
tests: ok

2023-08-01 14:02 UTC, merged