remove substation and it's voltage levels
gridsuite/network-modification-server pull request #282
Opened 2023-07-05 16:21 UTC by souissimai

2023-07-07 12:52 UTC, SlimaneAmar approved these changes

2023-07-07 12:52 UTC, SlimaneAmar commented on src/test/java/org/gridsuite/modification/server/modifications/SubstationDeletionTest.java
> +                .equipmentId("v2")
Replace by `l1`

2023-07-07 14:10 UTC, etiennehomer commented on src/test/java/org/gridsuite/modification/server/modifications/SubstationDeletionTest.java
> + * @author Etienne Homer <etienne.homer at rte-france.com>
It's your work, not mine :)

2023-07-21 15:15 UTC, dbraquart requested changes
code: ok, minor changes requested
tests: ok

2023-07-21 15:15 UTC, dbraquart commented on src/test/java/org/gridsuite/modification/server/ModificationControllerTest.java
> +            List.of(Pair.of(IdentifiableType.LINE, "line1"), Pair.of(IdentifiableType.LINE, "line3")), new HashSet<>(Set.of("s1", "s2"))
```suggestion
            List.of(Pair.of(IdentifiableType.LINE, "line1"), Pair.of(IdentifiableType.LINE, "line3")), Set.of("s1", "s2")
```

2023-07-21 15:15 UTC, dbraquart commented on src/test/java/org/gridsuite/modification/server/modifications/SubstationDeletionTest.java
> +        assertNull(getNetwork().getLine("line2"));
```suggestion
        assertNull(getNetwork().getLine("line1"));
        assertNull(getNetwork().getLine("line2"));
```

2023-07-21 15:15 UTC, dbraquart commented on src/test/java/org/gridsuite/modification/server/modifications/SubstationDeletionTest.java
> +        assertNotNull(getNetwork().getSubstation("s1"));
```suggestion
        assertNotNull(getNetwork().getSubstation("s1"));
        assertNotNull(getNetwork().getVoltageLevel("v1"));
        assertNotNull(getNetwork().getVoltageLevel("v2"));
        assertNotNull(getNetwork().getLoad("v1load"));
        assertNotNull(getNetwork().getLccConverterStation("v1lcc"));
        assertNotNull(getNetwork().getSwitch("v1d1"));
        assertNotNull(getNetwork().getLine("line1"));
        assertNotNull(getNetwork().getLine("line2"));
        assertNotNull(getNetwork().getHvdcLine("hvdcLine"));
```

2023-07-24 07:58 UTC, dbraquart approved these changes
code: ok
tests: not done with last commit

2023-07-24 07:59 UTC, merged