Adapt network preloading strategy when applying modifications
gridsuite/network-modification-server pull request #288
Opened 2023-07-07 14:15 UTC by FranckLecuyer

2023-07-10 15:36 UTC, SlimaneAmar requested changes

2023-07-11 08:50 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/modification/server/service/NetworkModificationService.java
> +    private PreloadingStrategy computePreloadingStrategy(List<ModificationInfos> modificationInfos) {
Done

2023-07-11 15:14 UTC, SlimaneAmar commented on src/main/java/org/gridsuite/modification/server/ModificationType.java
> +    public ModificationType maxStrategy(ModificationType other) {
Return `PreloadingStrategy`

2023-07-11 15:14 UTC, SlimaneAmar commented on src/main/java/org/gridsuite/modification/server/ModificationType.java
> +                || (strategy == PreloadingStrategy.COLLECTION && other.strategy == PreloadingStrategy.ALL_COLLECTIONS_NEEDED_FOR_BUS_VIEW)) ? other : this;
Invert the  last test ?

2023-07-11 15:22 UTC, SlimaneAmar commented on src/main/java/org/gridsuite/modification/server/ModificationType.java
> +    }
```
    public PreloadingStrategy maxStrategy(ModificationType other) {
        switch (strategy) {
            case NONE:
                if (other.strategy != PreloadingStrategy.NONE) {
                    return other.getStrategy();
                }
            case ALL_COLLECTIONS_NEEDED_FOR_BUS_VIEW:
                if (other.strategy == PreloadingStrategy.COLLECTION) {
                    return other.getStrategy();
                }
            default:
                return strategy;
        }
    }
```

2023-07-12 08:22 UTC, merged