Add the svc and vsc modifications in the voltage init modification
gridsuite/network-modification-server pull request #311
Opened 2023-08-11 15:11 UTC by FranckLecuyer

2023-08-17 17:50 UTC, dbraquart requested changes
code: 1 minor change request
tests: ok

2023-08-17 17:50 UTC, dbraquart commented on src/main/java/org/gridsuite/modification/server/modifications/VoltageInitModification.java
> +                Reporter reporter = subReporter.createSubReporter(STATIC_VAR_COMPENSATOR_MSG + s.getStaticVarCompensatorId(), GENERATOR_MSG + s.getStaticVarCompensatorId());
```suggestion
                Reporter reporter = subReporter.createSubReporter(STATIC_VAR_COMPENSATOR_MSG + s.getStaticVarCompensatorId(), STATIC_VAR_COMPENSATOR_MSG + s.getStaticVarCompensatorId());
```

2023-08-18 08:20 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/modification/server/modifications/VoltageInitModification.java
> +                Reporter reporter = subReporter.createSubReporter(STATIC_VAR_COMPENSATOR_MSG + s.getStaticVarCompensatorId(), GENERATOR_MSG + s.getStaticVarCompensatorId());
Fixed

2023-08-18 09:23 UTC, dbraquart reviewed
code: ok
tests: ok

2023-08-18 09:30 UTC, dbraquart approved these changes
code: ok
tests: ok

2023-08-18 13:40 UTC, ayolab approved these changes

2023-08-18 13:40 UTC, ayolab commented on src/main/java/org/gridsuite/modification/server/entities/equipment/modification/VoltageInitStaticVarCompensatorModificationEmbeddable.java
> + * Copyright (c) 2022, RTE (http://www.rte-france.com)
```suggestion
 * Copyright (c) 2023, RTE (http://www.rte-france.com)
```

2023-08-18 13:40 UTC, ayolab commented on src/main/java/org/gridsuite/modification/server/entities/equipment/modification/VoltageInitVscConverterStationModificationEmbeddable.java
> + * Copyright (c) 2022, RTE (http://www.rte-france.com)
```suggestion
 * Copyright (c) 2023, RTE (http://www.rte-france.com)
```

2023-08-18 13:40 UTC, ayolab commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +
remove white spaces

2023-08-18 14:06 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/modification/server/entities/equipment/modification/VoltageInitStaticVarCompensatorModificationEmbeddable.java
> + * Copyright (c) 2022, RTE (http://www.rte-france.com)
Fixed

2023-08-18 14:06 UTC, FranckLecuyer commented on src/main/resources/db/changelog/db.changelog-master.yaml
> +
Fixed

2023-08-18 14:13 UTC, merged