Reactive limits refactor
gridsuite/network-modification-server pull request #323
Opened 2023-09-11 07:34 UTC by YenguiSeddik

2023-09-13 09:29 UTC, FranckLecuyer requested changes

2023-09-13 09:29 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/modification/server/dto/BatteryCreationInfos.java
> -    @Schema(description = "Connection Name")
This move of connectionName, connectionDirection and connectionPosition fields up to InjectionCreationInfos class does not really concern the reactive limits refactoring ...
Same remark for the same move in the other dto classes and for the same move in the entity classes ...

2023-09-13 09:29 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/modification/server/dto/ReactiveLimitsHolderInfos.java
> +package org.gridsuite.modification.server.dto;
Missing license and header

2023-09-13 09:29 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/modification/server/modifications/BatteryCreation.java
> +        createReactiveLimits(batteryCreationInfos, battery, subReporterLimits);
ModificationUtils.getInstance().createReactiveLimits ? and no static keyword in this method call ?

2023-09-13 09:29 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/modification/server/modifications/GeneratorCreation.java
> +        createReactiveLimits(generatorCreationInfos, generator, subReporterLimits);
Same remark as above

2023-09-13 09:29 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/modification/server/modifications/ModificationUtils.java
> +    private static NetworkModificationException makeEquipmentException(NetworkModificationException.Type errorType,
remove static keyword and use singleton instance, to be consistent with the other method calls
same remark for the following methods ...

2023-09-18 13:50 UTC, FranckLecuyer approved these changes

2023-09-20 16:35 UTC, Walid-Sahnoun approved these changes
code ok
test ok

2023-09-21 07:46 UTC, merged