Add the shunt compensators modifications in the voltage init modification
gridsuite/network-modification-server pull request #324
Opened 2023-09-11 14:31 UTC by FranckLecuyer

2023-09-13 09:32 UTC, dbraquart requested changes
code: I propose a code simplification
tests: ok, but one remark (maybe a known issue):
 - in the logs tab, after modification build, we cannot see the MCS modifications in the right/tree part. We only see "Generator xxx" items.  EDIT: I meant in the "left/tree part" ;-)

2023-09-13 09:32 UTC, dbraquart commented on src/main/java/org/gridsuite/modification/server/modifications/VoltageInitModification.java
> +    private void applyShuntCompensatorModification(Network network, Reporter subReporter) {
The algo is a bit hard to read and has some duplicate lines. I propose you below a shortest version, strictly identical.

2023-09-13 09:32 UTC, dbraquart commented on src/main/java/org/gridsuite/modification/server/modifications/VoltageInitModification.java
> +                    }
```suggestion
                    if (m.getSectionCount() == null) {
                        reports.add(createReport("shuntCompensatorSectionCountUndefined", "Section count value is undefined", Map.of(), TypedValue.WARN_SEVERITY, 1));
                    } else if (m.getSectionCount() > 1) {
                        reports.add(createReport(SHUNT_SECTION_COUNT_VALUE_IGNORED_KEY, SHUNT_SECTION_COUNT_VALUE_CANNOT_BE_APPLIED, Map.of(VALUE, m.getSectionCount()), TypedValue.WARN_SEVERITY, 1));
                    } else if (currentSectionCount > 1) {
                        reports.add(createReport("shuntCompensatorCurrentSectionCountValueIgnored", "Current section count value ${value} should be 0 or 1", Map.of(VALUE, currentSectionCount), TypedValue.WARN_SEVERITY, 1));
                    } else {
                        if (m.getSectionCount() == 0) {
                            shuntCompensatorTerminal.disconnect();
                            reports.add(createReport("shuntCompensatorDisconnected", "Shunt compensator disconnected", Map.of(), TypedValue.INFO_SEVERITY, 1));
                        }
                        if (m.getSectionCount() != currentSectionCount) {
                            shuntCompensator.setSectionCount(m.getSectionCount());
                            reports.add(ModificationUtils.getInstance().buildModificationReportWithIndentation(currentSectionCount, m.getSectionCount(), SECTION_COUNT, 1));
                        }
                    }
```

2023-09-13 09:32 UTC, dbraquart commented on src/main/java/org/gridsuite/modification/server/modifications/VoltageInitModification.java
> +                    }
```suggestion
                    if (m.getConnect() == null) {
                        reports.add(createReport("shuntCompensatorConnectUndefined", "Connect value is undefined", Map.of(), TypedValue.WARN_SEVERITY, 1));
                    } else if (m.getSectionCount() > 1) {
                        reports.add(createReport(SHUNT_SECTION_COUNT_VALUE_IGNORED_KEY, SHUNT_SECTION_COUNT_VALUE_CANNOT_BE_APPLIED, Map.of(VALUE, m.getSectionCount()), TypedValue.WARN_SEVERITY, 1));
                    } else if (currentSectionCount > 1) {
                        reports.add(createReport("shuntCompensatorCurrentSectionCountValueIgnored", "Current section count value ${value} should be 0 or 1", Map.of(VALUE, currentSectionCount), TypedValue.WARN_SEVERITY, 1));
                    } else {
                        if (Boolean.TRUE.equals(m.getConnect()) && m.getSectionCount() == 1) {
                            shuntCompensatorTerminal.connect();
                            reports.add(createReport("shuntCompensatorReconnected", "Shunt compensator reconnected", Map.of(), TypedValue.INFO_SEVERITY, 1));
                        }
                        if (m.getSectionCount() != currentSectionCount) {
                            shuntCompensator.setSectionCount(m.getSectionCount());
                            reports.add(ModificationUtils.getInstance().buildModificationReportWithIndentation(currentSectionCount, m.getSectionCount(), SECTION_COUNT, 1));
                        }
                    }
```

2023-09-13 12:54 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/modification/server/modifications/VoltageInitModification.java
> +                    }
Done

2023-09-13 13:00 UTC, FranckLecuyer commented
> code: I propose a code simplification tests: ok, but one remark (maybe a known issue):
> 
>     * in the logs tab, after modification build, we cannot see the MCS modifications in the right/tree part. We only see "Generator xxx" items.

To have modifications on shunts, you must provide shunt compensators filter(s) in the settings : 
Voltage profile initialization --> Equipment selection --> Variable shunt compensators

Otherwise, no shunt will be modified ...

2023-09-14 07:23 UTC, dbraquart approved these changes
code: ok
tests: ok

2023-09-19 09:05 UTC, merged