Vsc creation
gridsuite/network-modification-server pull request #325
Opened 2023-09-11 14:39 UTC by YenguiSeddik

2023-09-13 10:53 UTC, FranckLecuyer requested changes

2023-09-13 10:53 UTC, FranckLecuyer commented on src/test/java/org/gridsuite/modification/server/modifications/VscCreationTest.java
> +        var test = getNetwork().getVoltageLevelStream().toList();
remove unused test variable

2023-09-13 10:53 UTC, FranckLecuyer commented on src/test/java/org/gridsuite/modification/server/modifications/VscCreationTest.java
> +                .filter(transformer -> transformer.getId().equals("stationId1")).count());
change 'transformer' variable name to converterStation

2023-09-13 10:53 UTC, FranckLecuyer commented on src/test/java/org/gridsuite/modification/server/modifications/VscCreationTest.java
> +                .filter(transformer -> transformer.getId().equals("stationId2")).count());
change 'transformer' variable name to converterStation

2023-09-13 10:53 UTC, FranckLecuyer commented on src/test/java/org/gridsuite/modification/server/modifications/VscCreationTest.java
> +                .filter(transformer -> transformer.getId().equals("stationId1")).count());
change 'transformer' variable name to converterStation

2023-09-13 10:53 UTC, FranckLecuyer commented on src/test/java/org/gridsuite/modification/server/modifications/VscCreationTest.java
> +                .filter(transformer -> transformer.getId().equals("stationId2")).count());
change 'transformer' variable name to converterStation

2023-09-13 10:53 UTC, FranckLecuyer commented on src/test/java/org/gridsuite/modification/server/modifications/VscCreationTest.java
> +    }
Add more checks on the the vsc characteristics, and on the vsc converter station 1 and station 2 characteristics ...

2023-09-13 12:36 UTC, FranckLecuyer requested changes

2023-09-13 12:36 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/modification/server/modifications/VscCreation.java
> +                createConvertStation(network, modificationInfos.getConverterStation1(), subReporter, "Converter station 1");
createConverterStation

2023-09-13 12:36 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/modification/server/modifications/VscCreation.java
> +                .withKey("converterStationCreated")
you cannot use the same key here for converter station 1 and converter station 2

2023-09-18 11:11 UTC, YenguiSeddik commented on src/main/java/org/gridsuite/modification/server/dto/ConverterStationCreationInfos.java
> +public class ConverterStationCreationInfos implements ReactiveLimitsHolderInfos {
done

2023-09-18 11:12 UTC, YenguiSeddik commented on src/main/java/org/gridsuite/modification/server/dto/VscCreationInfos.java
> +    private Float operatorActivePowerLimitSide1;
done

2023-09-18 11:12 UTC, YenguiSeddik commented on src/main/java/org/gridsuite/modification/server/dto/VscCreationInfos.java
> +    private Float operatorActivePowerLimitSide2;
done

2023-09-18 11:12 UTC, YenguiSeddik commented on src/main/java/org/gridsuite/modification/server/entities/equipment/creation/ConverterStationCreationEntity.java
> +public class ConverterStationCreationEntity {
done

2023-09-18 11:13 UTC, YenguiSeddik commented on src/main/java/org/gridsuite/modification/server/entities/equipment/creation/ConverterStationCreationEntity.java
> +@Table(name = "converterStationCreationEntity")
done

2023-09-18 11:16 UTC, YenguiSeddik commented on src/test/java/org/gridsuite/modification/server/modifications/VscCreationTest.java
> +        var test = getNetwork().getVoltageLevelStream().toList();
done

2023-09-18 14:02 UTC, FranckLecuyer requested changes

2023-09-18 14:02 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/modification/server/modifications/VscCreation.java
> +    private VscConverterStation createConvertStation(Network network,
createConverterStation

2023-09-20 16:21 UTC, Walid-Sahnoun approved these changes
code ok
test ok

2023-09-21 10:38 UTC, merged