Rename activePower and reactivePower for load Modification
gridsuite/network-modification-server pull request #394
Opened 2023-12-13 10:46 UTC by lilian-houdelet

2023-12-19 12:56 UTC, etiennehomer requested changes

2023-12-19 12:56 UTC, etiennehomer commented on src/main/java/org/gridsuite/modification/server/modifications/LoadModification.java
> +        ModificationUtils.getInstance().applyElementaryModifications(load::setP0, load::getP0, loadModificationInfos.getConstantActivePower(), subReporter, "Active power");
"Constant Active power"

"Constant Reactive power"

2023-12-19 12:56 UTC, etiennehomer commented on src/main/java/org/gridsuite/modification/server/modifications/LoadModification.java
> +        ModificationUtils.getInstance().applyElementaryModifications(load::setP0, load::getP0, loadModificationInfos.getConstantActivePower(), subReporter, "Active power");
"Constant Active power"

"Constant Reactive power"

2023-12-19 14:35 UTC, etiennehomer approved these changes

2023-12-20 16:58 UTC, ayolab approved these changes

2023-12-21 11:00 UTC, merged