Homogenize batteries and generators attributes
gridsuite/network-modification-server pull request #441
Opened 2024-02-17 08:28 UTC by souissimai

2024-02-26 15:26 UTC, Mathieu-Deharbe requested changes

2024-02-26 15:26 UTC, Mathieu-Deharbe commented on src/test/java/org/gridsuite/modification/server/modifications/GeneratorModificationTest.java
> +                        newPoint.setMaxQ(250.0);
C'est bizarre que `newPoint.setOldQmaxP(250.0);` soit remplacé par `newPoint.setMaxQ(250.0);` plutôt que par `newPoint.setOldMaxQ(250.0);`

Et bizarre que ça ne fasse pas planter le test.

2024-02-29 17:21 UTC, Mathieu-Deharbe approved these changes

2024-03-07 12:43 UTC, SlimaneAmar approved these changes

2024-03-07 14:01 UTC, merged