Trip and lockout hvdc lines
gridsuite/network-modification-server pull request #443
Opened 2024-02-20 09:59 UTC by ghazwarhili

2024-02-26 10:50 UTC, sBouzols requested changes
Could you add some UT please for those new cases ?
Will test

2024-02-26 14:13 UTC, EstherDarkish requested changes
java.lang.IllegalArgumentException: No enum constant org.gridsuite.modification.server.ModificationType.BRANCH_STATUS_MODIFICATION

When trying to display the list of modifications of my node in the frontend

2024-02-28 13:15 UTC, EstherDarkish approved these changes
Ok

2024-02-29 09:33 UTC, sBouzols commented on src/test/java/org/gridsuite/modification/server/modifications/OperatingStatusModificationLockoutHvdcLineTest.java
> +    }
Maybe we should add an assertNoOperatingStats which check if the extension is absent ?

2024-02-29 09:57 UTC, sBouzols commented on src/test/java/org/gridsuite/modification/server/modifications/OperatingStatusModificationLockoutHvdcLineTest.java
> +    }
add an assert to check if all terminals are connected ?

2024-03-01 08:10 UTC, sBouzols approved these changes
Code Review OK

2024-03-01 12:15 UTC, merged