add connectivity modification
gridsuite/network-modification-server pull request #495
Opened 2024-07-04 07:03 UTC by ghazwarhili

2024-07-17 14:50 UTC, etiennehomer requested changes

2024-08-07 14:20 UTC, thangqp commented on src/main/java/org/gridsuite/modification/server/modifications/ModificationUtils.java
> +            reports.add(buildModificationReport(null, connectionName, "Connection name"));
If pass null as old value, the report can not show an old value, see suggestion in this PR
https://github.com/gridsuite/network-modification-server/pull/513

2024-08-08 12:17 UTC, thangqp approved these changes
Code OK, Test OK

2024-08-09 14:32 UTC, etiennehomer approved these changes

2024-08-13 07:39 UTC, merged