Share code for network modifications
gridsuite/network-modification-server pull request #524
Opened 2024-08-28 08:44 UTC by Mathieu-Deharbe

2024-09-13 06:43 UTC, ghazwarhili commented on src/main/java/org/gridsuite/modification/server/modifications/VoltageLevelModification.java
> +        }
to optimize and refacto this code I suggest something like 

```
     private void updateShortCircuitLimits(ValueWrapper ipMin, ValueWrapper ipMax, Double oldIpMin, Double oldIpMax, IdentifiableShortCircuitAdder identifiableShortCircuitAdder, List<ModificationReport> reports) {
        updateShortCircuitLimit(ipMin, oldIpMin, "Low short circuit current limit", identifiableShortCircuitAdder::withIpMin, reports);
        updateShortCircuitLimit(ipMax, oldIpMax, "High short circuit current limit", identifiableShortCircuitAdder::withIpMax, reports);
    }

    private void updateShortCircuitLimit(ValueWrapper newValueWrapper, Double oldValue, String limitDescription,
                                         Consumer<Double> setterMethod, List<ModificationReport> reports) {
        Double newValue = (newValueWrapper != null) ? newValueWrapper.getValue() : null;

        if (newValue != null) {
            setterMethod.accept(newValue);
            Double oldValueToReport = convertToKiloAmps(oldValue);
            Double newValueToReport = convertToKiloAmps(newValue);

            reports.add(ModificationUtils.getInstance().buildModificationReport(oldValueToReport, newValueToReport, limitDescription));
        } else if (oldValue != null) {
            setterMethod.accept(oldValue);
        }
    }

    private Double convertToKiloAmps(Double value) {
        return (value != null) ? value * 0.001 : null;
    }
```

2024-09-13 06:43 UTC, ghazwarhili commented on src/main/java/org/gridsuite/modification/server/modifications/TwoWindingsTransformerModification.java
> +                        newMagnetizingConductanceToReport, "Magnetizing conductance", 1));
Use Constants for Keys

2024-09-17 08:50 UTC, EtienneLt requested changes
little comments

2024-09-17 08:50 UTC, EtienneLt commented on src/main/java/org/gridsuite/modification/server/modifications/TwoWindingsTransformerModification.java
> +    public static void modifyBranchFields(TwoWindingsTransformer twt, AttributeModification<Double> modifR, AttributeModification<Double> modifX, ReportNode reportNode) {
change name and maybe separate in two methods

2024-09-17 08:50 UTC, EtienneLt commented on src/main/java/org/gridsuite/modification/server/modifications/TwoWindingsTransformerModification.java
> +    public static void modifyBranchFields(TwoWindingsTransformer twt, AttributeModification<Double> modifR, AttributeModification<Double> modifX, ReportNode reportNode) {
one for R and one for X

2024-09-17 08:50 UTC, EtienneLt commented on src/main/java/org/gridsuite/modification/server/modifications/TwoWindingsTransformerModification.java
> +                targetDeadband, "Target deadband", 2);
the last value is often 2 maybe you could do a method with 2 as default value

2024-09-17 08:50 UTC, EtienneLt commented on src/test/java/org/gridsuite/modification/server/modifications/GeneratorByFormulaModificationTest.java
> +        assertEquals(2.5, generatorStartup1.getPlannedOutageRate(), 0);
why does it change ?

2024-09-18 10:47 UTC, Mathieu-Deharbe reviewed
Ok I renamed it to the whole `attributeModification`.

Many merge conflicts are solved in the last commits.

2024-09-18 10:50 UTC, Mathieu-Deharbe commented on src/main/java/org/gridsuite/modification/server/dto/formula/equipmentfield/BatteryField.java
> +        final AttributeModification<Double> modif = new AttributeModification<>(newValue, OperationType.SET);
Ok I renamed it to the whole attributeModification.

2024-09-18 10:51 UTC, Mathieu-Deharbe commented on src/main/java/org/gridsuite/modification/server/dto/formula/equipmentfield/TwoWindingsTransformerField.java
> +        final AttributeModification<Double> attrModif = new AttributeModification<>(newValue, OperationType.SET);
Ok I renamed it to the whole attributeModification.

2024-09-19 11:26 UTC, basseche approved these changes

2024-09-24 09:22 UTC, EtienneLt reviewed
few more comments and it is good for me

2024-09-24 09:22 UTC, EtienneLt commented on src/main/java/org/gridsuite/modification/server/modifications/GeneratorModification.java
> +                reportReactivePower = ModificationUtils.getInstance().applyElementaryModificationsAndReturnReport(generator::setTargetQ, generator::getTargetQ, modifTargetQ, "Reactive power");
should it be specified that it is **target** reactive power or setpoint ?

2024-09-25 11:02 UTC, EtienneLt approved these changes

2024-09-26 08:07 UTC, merged