upgrade powsybl network store to v1.16.0
gridsuite/network-modification-server pull request #527
Opened 2024-09-03 08:47 UTC by EtienneLt

2024-09-03 12:15 UTC, SlimaneAmar requested changes

2024-09-03 12:15 UTC, SlimaneAmar commented on pom.xml
> +            <!-- FIXME: network-store modules' version is overloaded in the dependencies section. The overloads and this property below have to be removed at next gridsuite-dependencies.version upgra
<dependency>
            <groupId>com.powsybl</groupId>
            <artifactId>powsybl-network-store-iidm-impl</artifactId>
            <version>1.16.0</version>
        </dependency>

2024-09-06 07:07 UTC, EtienneLt commented on src/test/java/org/gridsuite/modification/server/modifications/TwoWindingsTransformerModificationTest.java
> +//        changeConnectionState(getNetwork().getTwoWindingsTransformer("trf2"), TwoSides.TWO, true, true, null);
I dont know about this test @SlimaneAmar

2024-09-09 07:12 UTC, SlimaneAmar approved these changes

2024-09-09 13:25 UTC, merged