Remove hack and update report management
gridsuite/network-modification-server pull request #531
Opened 2024-09-06 09:39 UTC by ayolab

2024-09-06 14:32 UTC, TheMaskedTurtle requested changes

2024-09-06 14:32 UTC, TheMaskedTurtle commented on src/test/java/org/gridsuite/modification/server/modifications/CompositeModificationsTest.java
Not sure it should be here :grin:

2024-09-06 14:32 UTC, TheMaskedTurtle commented on src/test/java/org/gridsuite/modification/server/service/BuildTest.java
Same !

2024-09-07 21:03 UTC, ayolab commented on src/test/java/org/gridsuite/modification/server/modifications/CompositeModificationsTest.java
I hadn't finished fixing the tests yet :wink:

2024-09-12 16:10 UTC, dbraquart reviewed
code: 1 remark
tests : on going

2024-09-23 14:24 UTC, TheMaskedTurtle approved these changes

2024-09-26 13:07 UTC, merged