fix regulating when modifying phase tap changer
gridsuite/network-modification-server pull request #537
Opened 2024-09-24 07:29 UTC by EtienneLt

2024-09-26 12:29 UTC, Mathieu-Deharbe requested changes

2024-09-26 12:29 UTC, Mathieu-Deharbe commented on src/main/java/org/gridsuite/modification/server/modifications/TwoWindingsTransformerModification.java
> +        if (regulatingReport != null) {
```suggestion
        if (regulatingReport != null && regulationReports != null) {
```

2024-09-26 12:35 UTC, Mathieu-Deharbe requested changes
Doesn't compile anymore because of the recent merge of my refacto (that you reviewed) : https://github.com/gridsuite/network-modification-server/pull/524

Also can you please comment the ticket with your answers to the questions asked by the PO at the end of the orignal ticket ? I cannot understand if the issue is solved just with your code.

2024-09-26 12:35 UTC, Mathieu-Deharbe commented on src/main/java/org/gridsuite/modification/server/modifications/TwoWindingsTransformerModification.java
> +            phaseTapChangerInfos.getRegulating(), "Regulating", 2);
You will probably have to pass Regulating as a parameter now.

2024-10-02 12:50 UTC, Mathieu-Deharbe approved these changes
Small remark : I wonder how this "regulating" value is handled in this network modification now that we don't automatically set it to true. I didn't find how to modify it in the current interface.

Might be good to see this with a PO.

2024-10-03 16:40 UTC, thangqp commented
> Small remark : I wonder how this "regulating" value is handled in this network modification now that we don't automatically set it to true. I didn't find how to modify it in the current interface.
> 
> Might be good to see this with a PO.

Share the same question????

2024-10-11 12:29 UTC, Mathieu-Deharbe requested changes
I wrote a lot about the regulation mode. If this is not clear just ask me.

I also got a weird bug but I don't see how it could be caused by your code (even if I only get it on your branch) so I don't write it for now. If you wan't to see just ask. I think I m going to look a bit more into it.

2024-10-22 12:45 UTC, thangqp reviewed
Could you add an additional test method for the creation of extension, pls? with name e.g. testPhaseTapChangerRegulationCreation(), I see in the code coverage, it does not yet cover some required modification

2024-10-22 12:45 UTC, thangqp commented on src/test/java/org/gridsuite/modification/server/modifications/TwoWindingsTransformerModificationTest.java
> +            .andExpect(status().isOk()).andReturn();
```suggestion
            .andExpect(status().isOk());
```
result is not used, do not need .andReturn();

2024-10-22 12:45 UTC, thangqp commented on src/test/java/org/gridsuite/modification/server/modifications/TwoWindingsTransformerModificationTest.java
> +            .andExpect(status().isOk()).andReturn();
```suggestion
            .andExpect(status().isOk());
```

2024-10-22 12:45 UTC, thangqp commented on src/test/java/org/gridsuite/modification/server/modifications/TwoWindingsTransformerModificationTest.java
> +            .andExpect(status().isOk()).andReturn();
```suggestion
            .andExpect(status().isOk());
```

2024-10-22 12:45 UTC, thangqp commented on src/test/java/org/gridsuite/modification/server/modifications/TwoWindingsTransformerModificationTest.java
> +            .andExpect(status().isOk()).andReturn();
```suggestion
            .andExpect(status().isOk());
```

2024-10-22 12:45 UTC, thangqp commented on src/test/java/org/gridsuite/modification/server/modifications/TwoWindingsTransformerModificationTest.java
> +            .andExpect(status().isOk()).andReturn();
```suggestion
            .andExpect(status().isOk());
```

2024-10-22 12:45 UTC, thangqp commented on src/test/java/org/gridsuite/modification/server/modifications/TwoWindingsTransformerModificationTest.java
> +            .andExpect(status().isOk()).andReturn();
```suggestion
        mockMvc.perform(post(getNetworkModificationUri())
                .content(modificationToModifyJson1).contentType(MediaType.APPLICATION_JSON))
            .andExpect(status().isOk());
```

2024-10-22 12:45 UTC, thangqp commented on src/test/java/org/gridsuite/modification/server/modifications/TwoWindingsTransformerModificationTest.java
> +            result.getResponse().getContentAsString());
```suggestion
            assertLogMessage(new NetworkModificationException(MODIFY_TWO_WINDINGS_TRANSFORMER_ERROR, "Regulation value is missing, phase tap changer can not regulate").getMessage(),
            phaseTapChangerCreation.getErrorType().name(), reportService);
```

In my opinion, an assert on result is less interesting than an assert on log

2024-10-24 10:21 UTC, thangqp approved these changes
Test OK, Code OK

2024-10-24 14:28 UTC, Mathieu-Deharbe approved these changes

2024-10-25 08:48 UTC, merged