add checks on active power control creation
gridsuite/network-modification-server pull request #545
Opened 2024-10-14 14:57 UTC by EtienneLt

2024-10-16 16:03 UTC, ghazwarhili reviewed
We have to add the check only when modifying the equipment

2024-10-21 14:20 UTC, EtienneLt commented on src/main/java/org/gridsuite/modification/server/modifications/GeneratorModification.java
> +//        );
forgot to remove

2024-10-22 16:32 UTC, ghazwarhili requested changes

2024-10-22 16:32 UTC, ghazwarhili commented on src/main/java/org/gridsuite/modification/server/modifications/BatteryModification.java
> +            participate, droop, subReportNode, subReportNodeSetpoints, CREATE_BATTERY_ERROR, "Battery '" + battery.getId() + "' : ");
MODIFY_BATTERY_ERROR not CREATE_BATTERY_ERROR
and you can create const variable errorMessage for CREATE_BATTERY_ERROR, "Battery '" + battery.getId() + "' : "

2024-10-22 16:32 UTC, ghazwarhili commented on src/main/java/org/gridsuite/modification/server/dto/byfilter/equipmentfield/GeneratorField.java
> +                    MODIFY_GENERATOR_ERROR, "Generator '" + generator.getId() + "' : ");
you can create variable errorMessage for "Generator '" + generator.getId() + "' : "

2024-10-22 16:32 UTC, ghazwarhili commented on src/main/java/org/gridsuite/modification/server/dto/byfilter/equipmentfield/BatteryField.java
> +                    null, MODIFY_BATTERY_ERROR, "Battery '" + battery.getId() + "' : ");
create const variable errorMessage for "Generator '" + generator.getId() + "' : "

2024-10-22 16:32 UTC, ghazwarhili commented on src/main/java/org/gridsuite/modification/server/modifications/BatteryModification.java
> +import static org.gridsuite.modification.server.NetworkModificationException.Type.CREATE_BATTERY_ERROR;
remove

2024-10-22 16:32 UTC, ghazwarhili commented on src/main/java/org/gridsuite/modification/server/modifications/GeneratorModification.java
> +            MODIFY_GENERATOR_ERROR, "Generator '" + modificationInfos.getEquipmentId() + "' : ");
the same for errorMessage

2024-10-22 16:32 UTC, ghazwarhili commented on src/main/java/org/gridsuite/modification/server/modifications/ModificationUtils.java
> +        if (participate != null && droop != null) {
```suggestion
        Boolean participate = Optional.ofNullable(participateInfo).map(AttributeModification::getValue).orElse(null);
        Float droop = Optional.ofNullable(droopInfo).map(AttributeModification::getValue).orElse(null);
        checkActivePowerControl(participate, droop, exceptionType, errorMessage);
        if (participate != null && droop != null) {
            adder.withParticipate(participate)
                    .withDroop(droop)
                    .add();
            if (reports != null) {
                reports.add(buildModificationReport(null, participate, "Participate"));
                reports.add(buildModificationReport(Double.NaN, droop, "Droop"));
            }
        }
    }
```

2024-10-22 16:32 UTC, ghazwarhili commented on src/main/java/org/gridsuite/modification/server/modifications/ModificationUtils.java
> +            throw new NetworkModificationException(exceptionType, errorMessage + "for creation if participate is true, droop can not be null");
```suggestion
            if (Boolean.TRUE.equals(participate) && droop == null) {
            throw new NetworkModificationException(
                    exceptionType,
                    String.format("%s for creation: if participate is true, droop cannot be null", errorMessage)
            );
        }
```

2024-10-23 14:27 UTC, ghazwarhili approved these changes

2024-10-23 14:34 UTC, merged