US #689 shared definition with powsybl-network-conversion-server
gridsuite/network-modification-server pull request #56
Opened 2021-11-23 11:00 UTC by laurgarn

2021-11-25 12:51 UTC, FranckLecuyer reviewed
In your PR : https://github.com/powsybl/powsybl-network-conversion-server/pull/54/files
You have added an @Id annotation for 'id' field in VoltageLevelInfos dto class
and not here 
Is this an omission ?

2021-11-26 14:49 UTC, niconoir approved these changes

2021-11-26 14:52 UTC, FranckLecuyer approved these changes

2021-12-15 16:42 UTC, SlimaneAmar approved these changes

2021-12-15 16:42 UTC, SlimaneAmar approved these changes

2021-12-28 10:00 UTC, SlimaneAmar requested changes

2021-12-28 12:25 UTC, laurgarn commented on src/main/java/org/gridsuite/modification/server/dto/EquipmentInfos.java
>      String id;
Done

2021-12-30 09:41 UTC, laurgarn commented on src/main/java/org/gridsuite/modification/server/dto/EquipmentInfos.java
>      String id;
Done

2022-01-04 08:51 UTC, closed without merging