Use network-modification-library
gridsuite/network-modification-server pull request #561
Opened 2024-11-13 08:15 UTC by ayolab

2024-11-14 11:10 UTC, FranckLecuyer requested changes

2024-11-14 11:10 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/modification/server/mapper/ModificationMapper.java
> +        // TODO Auto-generated method stub
???
Maybe in progress ...

2024-11-18 15:38 UTC, ayolab commented on src/main/java/org/gridsuite/modification/server/mapper/ModificationMapper.java
> +        // TODO Auto-generated method stub
I changed the comment

2024-11-19 12:01 UTC, FranckLecuyer requested changes
Tests: unable to save a modificaton in GridExplore ...

ava.lang.NullPointerException: Name is null
gridstudy-network-modification-server-1           | 	at java.base/java.lang.Enum.valueOf(Unknown Source) ~[na:na]
gridstudy-network-modification-server-1           | 	at org.gridsuite.modification.ModificationType.valueOf(ModificationType.java:15) ~[gridsuite-network-modification-1.1.0-SNAPSHOT.jar:na]

La modification est bien créée dans la base du directory-server
La modification est créée dans la base du network-modification-server, mais elle n'a pas de date, ni de type, d'où le NullPointerException ...

2024-11-22 16:54 UTC, merged