Implement node realization
gridsuite/network-modification-server pull request #61
Opened 2021-12-14 11:00 UTC by FranckLecuyer

2021-12-22 09:53 UTC, SlimaneAmar commented
See comments for the design
I think also all the `transactional` annotations are not necessary

2021-12-22 09:54 UTC, SlimaneAmar requested changes

2021-12-22 09:54 UTC, SlimaneAmar commented on src/main/java/org/gridsuite/modification/server/service/NetworkModificationService.java
> +            switch (type) {
Need to have an object oriented approach ?
Review the design with a `Modification` interface and a class for each type which implements the interface
and a factory to create these classes
```
interface Modification {
    List<EquipmenModificationInfos> apply();
    
    void store();
}
```
1. For a modification from the front we create the modification then apply it and store it
2. For a realization get the modification from the database then  apply it only

The listener must be used only for the application.

2021-12-30 07:43 UTC, SlimaneAmar commented on src/main/java/org/gridsuite/modification/server/service/NetworkModificationService.java
> +        ReporterModel reporter = new ReporterModel("Realizaton", "Realization");
Typo

2022-01-03 09:55 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/modification/server/service/NetworkModificationService.java
> +        ReporterModel reporter = new ReporterModel("Realizaton", "Realization");
Corrected

2022-01-03 09:55 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/modification/server/service/RealizationWorkerService.java
> +        this.networkModificationService = Objects.requireNonNull(networkModificationService);
Done

2022-01-03 09:55 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/modification/server/service/RealizationExecContext.java
> +        Objects.requireNonNull(message);
Done

2022-01-03 09:55 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/modification/server/service/RealizationExecContext.java
> +        this.networkUuid = Objects.requireNonNull(networkUuid);
Done

2022-01-03 09:55 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/modification/server/service/RealizationCancelContext.java
> +        Objects.requireNonNull(message);
Done

2022-01-03 09:55 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/modification/server/service/RealizationCancelContext.java
> +        this.receiver = Objects.requireNonNull(receiver);
Done

2022-01-03 09:56 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/modification/server/service/RealizationStoppedPublisherService.java
> +    public void publish(String receiver, String stopMessage) {
Done

2022-01-03 09:56 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/modification/server/NetworkModificationController.java
> +    @PutMapping(value = "/realization/stop", produces = APPLICATION_JSON_VALUE)
Done

2022-01-03 09:56 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/modification/server/NetworkModificationController.java
> +    @PostMapping(value = "/networks/{networkUuid}/realization", produces = MediaType.APPLICATION_JSON_VALUE)
Done

2022-01-03 09:56 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/modification/server/service/RealizationWorkerService.java
> +            } catch (Exception exc) {
Removed

2022-01-03 09:58 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/modification/server/service/NetworkModificationService.java
> +            String startingVariant = StringUtils.isEmpty(originVariantId) ? VariantManagerConstants.INITIAL_VARIANT_ID : originVariantId;
Done

2022-01-03 10:01 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/modification/server/repositories/NetworkModificationRepository.java
> +    @Transactional(readOnly = true)
Removed

2022-01-03 10:12 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/modification/server/service/RealizationWorkerService.java
> +                    .flatMap(network -> execRealizeVariant(network, execContext.getNetworkUuid(), execContext.getReceiver(), realizationInfos))
Done

2022-01-03 10:39 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/modification/server/service/RealizationWorkerService.java
> +                realizationRequests.add(execContext.getReceiver()); // receiver is the node uuid to realize
Done

2022-01-03 10:39 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/modification/server/service/RealizationWorkerService.java
> +        if (receiver != null && cancelRealizationRequests.get(receiver) != null) {
Done

2022-01-04 16:15 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/modification/server/service/RealizationWorkerService.java
> +                    .onErrorResume(throwable -> {
Done

2022-01-07 13:10 UTC, SlimaneAmar approved these changes

2022-01-07 13:13 UTC, merged