Redesign modifications with groovy script and switch state modifications
gridsuite/network-modification-server pull request #64
Opened 2021-12-17 14:31 UTC by FranckLecuyer

…difications

Signed-off-by: Franck LECUYER <franck.lecuyer@rte-france.com>

2021-12-27 13:28 UTC, SlimaneAmar requested changes

2021-12-27 13:28 UTC, SlimaneAmar commented on src/main/java/org/gridsuite/modification/server/service/NetworkStoreListener.java
> +    public void addSubstationsIds(Set<String> substationsIds) {
Remove it and add VLs in the `onCreation` and the `deleteEquipmentInfos` methods
and rename `deleteEquipmentInfos` by `onTemporaryRemoval`

2022-01-03 15:39 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/modification/server/dto/GroovyScriptModificationInfos.java
> +    @Schema(description = "Substations ID")
Done

2022-01-03 15:39 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/modification/server/repositories/NetworkModificationRepository.java
> +    public GroovyScriptModificationInfos getGroovyScriptModification(UUID groupUuid, UUID modificationUuid) {
Removed

2022-01-03 15:44 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/modification/server/service/NetworkModificationService.java
> +                listener.addSubstationsIds(NetworkStoreListener.getSubstationIds(aSwitch));
Removed

2022-01-03 15:48 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/modification/server/service/NetworkStoreListener.java
Removed

2022-01-03 15:50 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/modification/server/service/NetworkStoreListener.java
>      private Set<String> getSubstationsIds(String equipmentId) {
Removed

2022-01-03 15:57 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/modification/server/NetworkModificationController.java
>      @ApiResponses(value = {@ApiResponse(responseCode = "200", description = "The equipment state has been changed")})
Done

2022-01-03 16:00 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/modification/server/NetworkModificationController.java
> +    public ResponseEntity<Flux<ModificationInfos>> applyGroovyScript(@Parameter(description = "Network UUID") @PathVariable("networkUuid") UUID networkUuid,
study-server only have to know the substations ids involved in the modification ...

2022-01-03 16:04 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/modification/server/entities/GroovyScriptModificationEntity.java
> +    public GroovyScriptModificationInfos toModificationInfos() {
Removed

2022-01-03 16:24 UTC, FranckLecuyer commented on src/test/java/org/gridsuite/modification/server/ModificationRepositoryTest.java
>          assertEquals(3, modificationInfos.size());
Done

2022-01-03 16:28 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/modification/server/repositories/NetworkModificationRepository.java
> +    public GroovyScriptModificationInfos getGroovyScriptModification(UUID groupUuid, UUID modificationUuid) {
Used in ModificationRepositoryTest now

2022-01-03 16:28 UTC, FranckLecuyer commented on src/main/java/org/gridsuite/modification/server/entities/GroovyScriptModificationEntity.java
> +    public GroovyScriptModificationInfos toModificationInfos() {
Used in ModificationRepositoryTest now

2022-01-04 10:44 UTC, SlimaneAmar commented on src/main/java/org/gridsuite/modification/server/repositories/NetworkModificationRepository.java
> +    public GroovyScriptModificationInfos getGroovyScriptModification(UUID groupUuid, UUID modificationUuid) {
Better to move in the class test ?
Like testStatusLineModification in https://github.com/gridsuite/network-modification-server/pull/67

2022-01-04 10:50 UTC, SlimaneAmar commented on src/main/java/org/gridsuite/modification/server/service/NetworkStoreListener.java
> +    public void addSubstationsIds(Set<String> substationsIds) {
Done in https://github.com/gridsuite/network-modification-server/pull/67

2022-01-04 10:53 UTC, SlimaneAmar commented on src/main/java/org/gridsuite/modification/server/repositories/NetworkModificationRepository.java
> +    public GroovyScriptModificationInfos getGroovyScriptModification(UUID groupUuid, UUID modificationUuid) {
Better to move in the class test ?
Like testStatusLineModification in https://github.com/gridsuite/network-modification-server/pull/67

2022-01-04 10:55 UTC, SlimaneAmar commented on src/main/java/org/gridsuite/modification/server/repositories/NetworkModificationRepository.java
> +    public GroovyScriptModificationInfos getGroovyScriptModification(UUID groupUuid, UUID modificationUuid) {
Better to move in the class test ?
Like testStatusLineModification in https://github.com/gridsuite/network-modification-server/pull/67

2022-01-04 10:56 UTC, SlimaneAmar commented on src/main/java/org/gridsuite/modification/server/repositories/NetworkModificationRepository.java
> +    public GroovyScriptModificationInfos getGroovyScriptModification(UUID groupUuid, UUID modificationUuid) {
Better to move in the class test ?
Like testStatusLineModification in #67

2022-01-07 14:51 UTC, SlimaneAmar approved these changes

2022-01-07 14:56 UTC, merged