US 755 add linear shunt compensator creation
gridsuite/network-modification-server pull request #75
Opened 2022-01-25 15:45 UTC by JacquesBorsenberger

Signed-off-by: jacques borsenberger <jacques.borsenberger@rte-france.com>

2022-01-26 16:39 UTC, niconoir requested changes

2022-01-27 06:47 UTC, JacquesBorsenberger commented on src/main/java/org/gridsuite/modification/server/dto/ShuntCompensatorCreationInfos.java
> + * Copyright (c) 2020, RTE (http://www.rte-france.com)
done

2022-01-27 06:47 UTC, JacquesBorsenberger commented on src/main/java/org/gridsuite/modification/server/dto/ShuntCompensatorCreationInfos.java
> + * @author Franck Lecuyer <franck.lecuyer at rte-france.com>
done

2022-01-27 06:47 UTC, JacquesBorsenberger commented on src/main/java/org/gridsuite/modification/server/entities/equipment/creation/BranchCreationEntity.java
> +        foreignKey = @ForeignKey(), nullable = true)
removed change

2022-01-27 06:47 UTC, JacquesBorsenberger commented on src/main/java/org/gridsuite/modification/server/entities/equipment/creation/BranchCreationEntity.java
> +        foreignKey = @ForeignKey(), nullable = true)
removed change

2022-01-27 07:42 UTC, JacquesBorsenberger commented on src/test/java/org/gridsuite/modification/server/utils/MatcherShuntCompensatorCreationInfos.java
> + * Copyright (c) 2021, RTE (http://www.rte-france.com)
done

2022-01-27 07:43 UTC, JacquesBorsenberger commented on src/test/java/org/gridsuite/modification/server/utils/MatcherShuntCompensatorCreationInfos.java
> + * @author Sylvain Bouzols <sylvain.bouzols at rte-france.com>
done

2022-01-27 07:52 UTC, JacquesBorsenberger commented on src/main/java/org/gridsuite/modification/server/service/NetworkStoreListener.java
> +    public void storeShuntCompensatorCreation(ShuntCompensatorCreationInfos shuntCompensatorCreationInfos) {
done

2022-01-27 07:52 UTC, JacquesBorsenberger commented on src/main/java/org/gridsuite/modification/server/entities/equipment/creation/ShuntCompensatorCreationEntity.java
> +    public ShuntCompensatorCreationInfos toEquipmentModificationInfos(Set<String> uuids) {
done

2022-01-27 13:46 UTC, niconoir approved these changes

2022-01-28 10:28 UTC, etiennehomer approved these changes

2022-01-28 10:38 UTC, etiennehomer commented on src/test/java/org/gridsuite/modification/server/ModificationRepositoryTest.java
> +        SQLStatementCountValidator.reset();
is it pertinent to test modification deletion for each type of equipment ? 
It could be test once in a test on modification

2022-01-28 14:10 UTC, merged