Edit form modification [WIP]
gridsuite/network-modification-server pull request #81
Opened 2022-03-14 12:53 UTC by etiennehomer

2022-04-01 13:53 UTC, sBouzols requested changes

2022-04-01 13:53 UTC, sBouzols commented on src/main/java/org/gridsuite/modification/server/service/NetworkModificationService.java
> +            return Mono.error(new NetworkModificationException(CREATE_LOAD_ERROR, "Generator creation not found"));
CREATE_GENERATOR_ERROR ?

2022-04-01 13:53 UTC, sBouzols commented on src/main/java/org/gridsuite/modification/server/service/NetworkModificationService.java
> +            return Mono.error(new NetworkModificationException(CREATE_LOAD_ERROR, "Line creation not found"));
CREATE_LINE_ERROR

2022-04-01 13:53 UTC, sBouzols commented on src/main/java/org/gridsuite/modification/server/service/NetworkModificationService.java
> +                networkModificationRepository,
indentation

2022-04-01 13:53 UTC, sBouzols commented on src/main/java/org/gridsuite/modification/server/service/NetworkModificationService.java
> +            return Mono.error(new NetworkModificationException(CREATE_LOAD_ERROR, "Shunt compensator creation not found"));
CREATE_SHUNT_COMPENSATOR_ERROR ?

2022-04-01 13:53 UTC, sBouzols commented on src/main/java/org/gridsuite/modification/server/repositories/NetworkModificationRepository.java
> +        modifications.forEach(modificationGroupEntity::addModification);
You don't need the saveAll anymore ?

2022-04-01 13:53 UTC, sBouzols commented on src/main/java/org/gridsuite/modification/server/NetworkModificationController.java
> +    @PutMapping(value = "/voltage-levels", consumes = MediaType.APPLICATION_JSON_VALUE, produces = MediaType.APPLICATION_JSON_VALUE)
Add the voltage-levelUuid in path for a PUT Request

2022-04-04 14:20 UTC, AbdelHedhili commented on src/main/java/org/gridsuite/modification/server/service/NetworkModificationService.java
> +            return Mono.error(new NetworkModificationException(CREATE_LOAD_ERROR, "Generator creation not found"));
yep, fixed

2022-04-04 14:26 UTC, AbdelHedhili commented on src/main/java/org/gridsuite/modification/server/repositories/NetworkModificationRepository.java
> +        modifications.forEach(modificationGroupEntity::addModification);
No need indeed

2022-04-06 15:04 UTC, sBouzols approved these changes

2022-04-06 15:05 UTC, AbdelHedhili approved these changes

2022-04-06 15:12 UTC, merged